ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "weatherPushEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "weatherCheckIntervalMinutes" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "weatherLastCheckedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "weatherAlertKeys" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
