/** 25 фактов — перенос из прежнего fun-facts.ts (категории → slug). */
export const LEGACY_FUN_FACTS: {
  slug: string;
  categorySlug: string;
  emoji: string;
  title: string;
  text: string;
  sortOrder: number;
}[] = [
  {
    slug: "fact-tomato-berry",
    categorySlug: "science",
    emoji: "🍅",
    title: "Томат — это ягода",
    text: "С ботанической точки зрения томат — это ягода, а не овощ. Но в 1893 году Верховный суд США постановил считать его овощем для таможенных целей.",
    sortOrder: 0,
  },
  {
    slug: "fact-cucumber-water",
    categorySlug: "science",
    emoji: "🥒",
    title: "Огурец на 96% состоит из воды",
    text: "Огурец — один из самых «водянистых» овощей. Он отлично утоляет жажду и содержит всего около 15 ккал на 100 г.",
    sortOrder: 1,
  },
  {
    slug: "fact-carrot-purple",
    categorySlug: "history",
    emoji: "🥕",
    title: "Морковь была фиолетовой",
    text: "До XVII века морковь была фиолетовой или белой. Оранжевую вывели голландские селекционеры в честь Вильгельма Оранского.",
    sortOrder: 2,
  },
  {
    slug: "fact-sunflower-heliotropism",
    categorySlug: "science",
    emoji: "🌻",
    title: "Подсолнух поворачивается за солнцем",
    text: "Молодые подсолнухи следят за солнцем (гелиотропизм), но взрослые растения фиксируются лицом на восток — так они привлекают больше опылителей утром.",
    sortOrder: 3,
  },
  {
    slug: "fact-pepper-ripening",
    categorySlug: "plants",
    emoji: "🫑",
    title: "Зелёный и красный перец — одно растение",
    text: "Зелёный болгарский перец — это незрелый красный. Чем спелее перец, тем он слаще и богаче витамином C.",
    sortOrder: 4,
  },
  {
    slug: "fact-potato-space",
    categorySlug: "history",
    emoji: "🥔",
    title: "Картофель в космосе",
    text: "В 1995 году картофель стал одной из культур, выращенных на орбите в рамках экспериментов по космической биологии.",
    sortOrder: 5,
  },
  {
    slug: "fact-strawberry-seeds-outside",
    categorySlug: "science",
    emoji: "🍓",
    title: "Семена клубники снаружи",
    text: "У привычной садовой клубники много семян на поверхности плода — это особенность строения соплодия.",
    sortOrder: 6,
  },
  {
    slug: "fact-garlic-pests",
    categorySlug: "plants",
    emoji: "🧄",
    title: "Чеснок отпугивает вредителей",
    text: "Фитонциды чеснока отпугивают часть вредителей; посадка рядом с розами и томатами иногда снижает давление тли.",
    sortOrder: 7,
  },
  {
    slug: "fact-bamboo-growth",
    categorySlug: "records",
    emoji: "🌱",
    title: "Бамбук — рекордсмен по росту",
    text: "Некоторые виды бамбука прибавляют почти метр в сутки в пик сезона — среди деревьев и трав это редкое сочетание скорости и высоты.",
    sortOrder: 8,
  },
  {
    slug: "fact-pumpkin-record",
    categorySlug: "records",
    emoji: "🎃",
    title: "Гигантские тыквы на выставках",
    text: "На конкурсах в США и Европе фиксируют тыквы весом более тонны — результат селекции и интенсивного ухода.",
    sortOrder: 9,
  },
  {
    slug: "fact-pea-tendrils",
    categorySlug: "science",
    emoji: "🫛",
    title: "Горох цепляется усиками",
    text: "Усики гороха обвивают опору за счёт тигмотропизма — рост в сторону касания.",
    sortOrder: 10,
  },
  {
    slug: "fact-watermelon-cucumber-family",
    categorySlug: "plants",
    emoji: "🍉",
    title: "Арбуз — родственник огурца",
    text: "Оба относятся к семейству тыквенных наряду с кабачком и дыней.",
    sortOrder: 11,
  },
  {
    slug: "fact-cabbage-vitamin-c",
    categorySlug: "history",
    emoji: "🥬",
    title: "Квашеная капуста и витамин C",
    text: "Квашеная капуста сохраняет заметное количество витамина C; в прошлом её ценили в длительных плаваниях.",
    sortOrder: 12,
  },
  {
    slug: "fact-dill-beneficial-insects",
    categorySlug: "plants",
    emoji: "🌿",
    title: "Укроп для полезных насекомых",
    text: "Цветущий укроп привлекает златоглазок и хищных жуков — помощников против тли.",
    sortOrder: 13,
  },
  {
    slug: "fact-eggplant-nightshade",
    categorySlug: "science",
    emoji: "🍆",
    title: "Баклажан в семействе паслёновых",
    text: "Как и картофель с томатом, баклажан относится к паслёным; в листьях есть алкалоиды, плод в пищу безопасен при обычной готовке.",
    sortOrder: 14,
  },
  {
    slug: "fact-corn-domestication",
    categorySlug: "history",
    emoji: "🌽",
    title: "Кукуруза — древняя культура",
    text: "Одомашнивание кукурузы в Америках насчитывает тысячи лет; без неё не сложились бы многие кухни мира.",
    sortOrder: 15,
  },
  {
    slug: "fact-beans-nitrogen",
    categorySlug: "soil",
    emoji: "🫘",
    title: "Бобовые обогащают почву азотом",
    text: "Симбиоз с клубеньковыми бактериями позволяет бобовым фиксировать азот — после них грядка благоприятнее для «тяжелой» культуры.",
    sortOrder: 16,
  },
  {
    slug: "fact-apple-longevity",
    categorySlug: "records",
    emoji: "🍎",
    title: "Яблони живут десятилетиями",
    text: "Хорошо ухоженная яблоня плодоносит многие десятилетия; в мире есть знаменитые старые экземпляры.",
    sortOrder: 17,
  },
  {
    slug: "fact-broccoli-sulforaphane",
    categorySlug: "science",
    emoji: "🥦",
    title: "Брокколи и сульфорафан",
    text: "Лёгкая термообработка сохраняет больше полезных соединений, чем долгое кипячение; пар 3–5 минут — разумный компромисс.",
    sortOrder: 18,
  },
  {
    slug: "fact-russia-dachas",
    categorySlug: "world",
    emoji: "🏡",
    title: "Дачные участки в России",
    text: "Миллионы семей ведут огород на садовых и дачных участках — уникальный по масштабу культурный и продовольственный пласт.",
    sortOrder: 19,
  },
  {
    slug: "fact-bee-pollination",
    categorySlug: "harvest",
    emoji: "🐝",
    title: "Пчёлы и урожай",
    text: "Опыление медоносными насекомыми критично для части культур; медоносы на грядке повышают завязь у многих овощей и ягод.",
    sortOrder: 20,
  },
  {
    slug: "fact-moon-calendar",
    categorySlug: "history",
    emoji: "🌙",
    title: "Лунный календарь на грядке",
    text: "Гравитация Луны влияет на приливы; в садоводстве споры о «лунных» сроках посева продолжаются, но климат и почва решают больше.",
    sortOrder: 21,
  },
  {
    slug: "fact-mulch-water",
    categorySlug: "harvest",
    emoji: "💧",
    title: "Мульча и влага",
    text: "Органическая мульча резко снижает испарение с поверхности почвы в жару и подавляет часть сорняков.",
    sortOrder: 22,
  },
  {
    slug: "fact-compost-speed",
    categorySlug: "harvest",
    emoji: "🪴",
    title: "Компост за пару месяцев",
    text: "При балансе углерода и азота, влажности 50–60% и перемешивании компост «созревает» за 6–8 недель теплого сезона.",
    sortOrder: 23,
  },
  {
    slug: "fact-pepper-scoville",
    categorySlug: "records",
    emoji: "🌶️",
    title: "Острота перца в сковиллах",
    text: "Шкала Сковилла измеряет концентрацию капсаицина: от нуля у сладкого перца до миллионов у суперострых сортов.",
    sortOrder: 24,
  },
];
