/** Дополнительные лайфхаки (новые, без пересечения по смыслу с базовыми 20). */
export const EXTRA_GUIDE_HACKS: {
  slug: string;
  categorySlug: string;
  title: string;
  text: string;
  imageUrl: string;
  imageAlt: string;
  sortOrder: number;
}[] = [
  {
    slug: "hack-iodine-seeds",
    categorySlug: "growing-secrets",
    title: "Слабый йод для проращивания семян",
    text: "На литр тёплой воды — 1–2 капли йода (не больше): замачивание 2–4 часа для тыквы, кабачка, фасоли ускоряет набухание оболочки. Для мелких семян время сокращайте; после замачивания промойте чистой водой.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Compost_heap.jpg",
    imageAlt: "Огород и почва",
    sortOrder: 100,
  },
  {
    slug: "hack-peroxide-sanitize-tray",
    categorySlug: "growing-secrets",
    title: "Перекись для дезинфекции лотков под рассаду",
    text: "Перед посевом пластиковые кассеты и крышки протирают раствором 3% перекиси 1:10 с водой, смывают чистой водой и сушат. Снижает риск «чёрной ножки» без агрессивной химии.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Onions.jpg",
    imageAlt: "Рассада и посуда",
    sortOrder: 101,
  },
  {
    slug: "hack-soap-spray-aphid",
    categorySlug: "pests-diseases-care",
    title: "Хозяйственное мыло против тли",
    text: "20–30 г натёртого мыла на 1 л тёплой воды, тщательно растворить и опрыскать поражённые листья вечером. Повтор через 3–4 дня; не смешивайте с медью и жёсткими фунгицидами в одной бутылке.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/Nasturtium_flower_orange.jpg",
    imageAlt: "Цветы на грядке",
    sortOrder: 102,
  },
  {
    slug: "hack-milk-mildew",
    categorySlug: "pests-diseases-care",
    title: "Молочно-водяной спрей от мучнистой росы",
    text: "Сырое молоко 1:9 с водой — лёгкое опрыскивание огурцов, кабачков и кустов смородины в сухую погоду. Повторять каждые 5–7 дней; при сильном поражении комбинируйте с санитарной обрезкой.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Mustard_Fields.jpg",
    imageAlt: "Поле и растения",
    sortOrder: 103,
  },
  {
    slug: "hack-soda-cabbage-white",
    categorySlug: "pests-diseases-care",
    title: "Сода и соль по капусте от бабочки белянки",
    text: "Сухую смесь пищевой соды и крупной соли 1:1 осторожно втирают в сердечко кочана при первых дырочках от гусениц. Механический барьер и щелочная среда отпугивают часть гусениц; тяжёлое заражение — сбор вручную + сетка.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Compost_heap.jpg",
    imageAlt: "Огород",
    sortOrder: 104,
  },
  {
    slug: "hack-charcoal-pot-drainage",
    categorySlug: "growing-secrets",
    title: "Древесный уголь на дно горшка",
    text: "Крупные куски древесного угля (не брикеты для шашлыка с химией) кладут на дренажный слой: держит воздух, впитывает лишнюю влагу и часть запахов. Подходит для крупных контейнеров с цитрусами и пеларгониями зимой.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Woodchips.jpg",
    imageAlt: "Органический материал",
    sortOrder: 105,
  },
  {
    slug: "hack-sand-carrot-mix",
    categorySlug: "growing-secrets",
    title: "Семена моркови с песком для равномерного сева",
    text: "Мелкие семена смешивают с сухим речным песком в пропорции 1:5–1:10 и рассыпают бороздку — реже приходится прореживать. Песок держит влагу у семян первые дни.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Pine_needles.jpg",
    imageAlt: "Природные материалы",
    sortOrder: 106,
  },
  {
    slug: "hack-potato-chitting",
    categorySlug: "growing-secrets",
    title: "Проращивание клубней картофеля на свету",
    text: "За 3–5 недель до посадки клубни выкладывают в один слой в прохладном светлом месте: ростки короткие и крепкие, не ломаются при посадке. Тёмное проращивание даёт длинные хрупкие «свечи».",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Garlic_bulbs.jpg",
    imageAlt: "Луковицы и клубни",
    sortOrder: 107,
  },
  {
    slug: "hack-phacelia-after-dig",
    categorySlug: "soil-compost-mulch",
    title: "Фацелия после тяжёлой культуры",
    text: "Фацелию сеют сразу после уборки чеснока или раннего картофеля: корни рыхлят почву, цветы кормят пчёл, зелёную массу заделывают или оставляют мульчей. Отличный «переход» между сезонами.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Mustard_Fields.jpg",
    imageAlt: "Медоносное поле",
    sortOrder: 108,
  },
  {
    slug: "hack-rye-winter-cover",
    categorySlug: "soil-compost-mulch",
    title: "Озимая рожь как зелёный защитный покров",
    text: "Рожь сеют под зиму на оголённой грядке: корни держат структуру почвы от вымывания, весной скашивают зелёную массу в заделку. Альтернатива голой земле на уклонах.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Hay_bale.jpg",
    imageAlt: "Сено на поле",
    sortOrder: 109,
  },
  {
    slug: "hack-sawdust-nitrogen",
    categorySlug: "soil-compost-mulch",
    title: "Свежие опилки только с азотной добавкой",
    text: "Чистые опилки вытягивают азот при разложении. Закладывая их в компост или в траншею, добавляйте слой навоза, зелёной травы или мочевину по инструкции; иначе грядка «голодная» первый год.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Woodchips.jpg",
    imageAlt: "Щепа и опилки",
    sortOrder: 110,
  },
  {
    slug: "hack-calendula-border",
    categorySlug: "pests-diseases-care",
    title: "Календула по периметру теплицы",
    text: "Низкорослую календуру сеют у входа и по углам: аромат отпугивает часть белокрылок и привлекает полезных насекомых. Не заменяет проветривание и ловушки при сильном нашествии.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Tagetes_erecta_flower.jpg",
    imageAlt: "Яркие цветы",
    sortOrder: 111,
  },
  {
    slug: "hack-wormwood-decoction",
    categorySlug: "folk-simple",
    title: "Настой полыни от муравьёв и слизней (точечно)",
    text: "Горькую полынь заливают кипятком, настаивают сутки, разбавляют 1:3 и поливают дорожки и кромки грядок. Горечь отпугивает; не лейте на корни любимых культур крупными дозами.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Urtica_dioica_pokr%C3%B3j2_23.06.2012_p.jpg",
    imageAlt: "Дикорастущие травы",
    sortOrder: 112,
  },
  {
    slug: "hack-honey-rooting",
    categorySlug: "folk-simple",
    title: "Разведённый мёд для черенков (осторожно)",
    text: "Чайная ложка мёда на стакан тёплой воды — короткое замачивание основания черенка смородины или винограда перед посадкой в песок. Сахара стимулируют корнеобразование у части культур; не храните раствор неделями.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Banana_peel.jpg",
    imageAlt: "Органика",
    sortOrder: 113,
  },
  {
    slug: "hack-tyre-raised-visual",
    categorySlug: "plot-improvement",
    title: "Шина как временная высокая грядка",
    text: "Старые покрышки без трещин выкладывают кольцом, на дно — дренаж, затем почву. Удобно для тёплой рассады дынь и баклажанов; следите, чтобы не накапливалась влага у стенок в холодную весну.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Wooden_pallet.jpg",
    imageAlt: "Материалы для грядок",
    sortOrder: 114,
  },
  {
    slug: "hack-bottle-cloche",
    categorySlug: "growing-secrets",
    title: "Пластиковая бутылка как мини-парник",
    text: "Дно от 5-литровой бутылки срезают, накрывают рассаду в грунте на ночь при угрозе заморозка. Днём приоткрывайте или снимайте, чтобы не перегреть.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Bottle_irrigation.jpg",
    imageAlt: "Пластик на грядке",
    sortOrder: 115,
  },
  {
    slug: "hack-shade-cloth-pepper",
    categorySlug: "growing-secrets",
    title: "Лёгкое затенение перца в жару",
    text: "В полуденные часы при +30 °C и ярком солнце перец сбрасывает цветки. Белое агроволокно 17–30 g/m² на дуге на 2–3 часа снимает стресс; не затеняйте весь день.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Mustard_Fields.jpg",
    imageAlt: "Поле под солнцем",
    sortOrder: 116,
  },
  {
    slug: "hack-row-cover-early",
    categorySlug: "growing-secrets",
    title: "Лутрасил или спанбонд на дугах для ранних салатов",
    text: "Плотность 30–40 удерживает ночной теплый слой и защищает от ветра; снимайте или приоткрывайте днём при +15 °C и выше, чтобы не вытянулась рассада.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Compost_heap.jpg",
    imageAlt: "Огород весной",
    sortOrder: 117,
  },
  {
    slug: "hack-alfalfa-tea",
    categorySlug: "soil-compost-mulch",
    title: "Настой люцерны или сена",
    text: "Гранулированную люцерну или немного сена заливают водой на 3–5 дней, разбавляют 1:5 и поливают под корень в фазу завязи. Мягкая подкормка азотом и микроэлементами.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Hay_bale.jpg",
    imageAlt: "Сено",
    sortOrder: 118,
  },
  {
    slug: "hack-chamomile-fungus-seedling",
    categorySlug: "folk-simple",
    title: "Слабый отвар ромашки для полива рассады",
    text: "Аптекарскую ромашку заваривают как чай, охлаждают и разбавляют водой 1:2 — полив раз в неделю от грибковых пятен на сеянцах. При осложнениях используйте биопрепараты.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Onions.jpg",
    imageAlt: "Рассада",
    sortOrder: 119,
  },
  {
    slug: "hack-cinnamon-damping",
    categorySlug: "folk-simple",
    title: "Корица на поверхность грунта в кассетах",
    text: "Тонкий слой молотой корицы после посева легонько вдавливают — сдерживает плесень на торфяных субстратах при избыточном поливе. Проветривание важнее примочки.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Baking_yeast_cells_under_40x_microscope_objective.jpg",
    imageAlt: "Мелкий порошок",
    sortOrder: 120,
  },
  {
    slug: "hack-zeolite-compost",
    categorySlug: "soil-compost-mulch",
    title: "Цеолит в компостную кучу",
    text: "Гранулированный цеолит впитывает аммиак и уменьшает запах; добавляют горстями между слоями зелёной массы. Готовый компост становится рыхлее.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Vermicompost.jpg",
    imageAlt: "Компостирование",
    sortOrder: 121,
  },
  {
    slug: "hack-perlite-seedlings",
    categorySlug: "growing-secrets",
    title: "Перлит в верхний слой пикировки",
    text: "После пикировки томата или перца посыпают влажным перлитом стебель у корня — меньше испарения и грибка «на шейке». Полив под корень, не на листья.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Pine_needles.jpg",
    imageAlt: "Субстрат",
    sortOrder: 122,
  },
  {
    slug: "hack-coconut-coir-seed",
    categorySlug: "growing-secrets",
    title: "Кокосовый субстрат для капризных семян",
    text: "Промытую кокосовую крошку смешивают с перлитом 2:1 для петуний и бакопы: стабильная влажность без переувлажнения торфа.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Banana_peel.jpg",
    imageAlt: "Натуральные материалы",
    sortOrder: 123,
  },
  {
    slug: "hack-lime-sulfur-winter",
    categorySlug: "pests-diseases-care",
    title: "Железный или медный купорос по инструкции ранней весной",
    text: "Обработки по спящим почкам ягодников и плодовых снижают инокулум грибков; строго соблюдайте дозировку и температуру на этикетке, не смешивайте с неизвестными препаратами.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Vinegar.jpg",
    imageAlt: "Растворы для сада",
    sortOrder: 124,
  },
  {
    slug: "hack-sticky-yellow-traps",
    categorySlug: "pests-diseases-care",
    title: "Жёлтые липкие ловушки на уровне листвы",
    text: "В теплице ловушки ставят чуть выше растений на южной стороне — ловят белокрылку и мошек. В открытом грунте учитывайте полезных опылителей, не вешайте на каждый куст.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/Nasturtium_flower_orange.jpg",
    imageAlt: "Растения в теплице",
    sortOrder: 125,
  },
  {
    slug: "hack-mulch-garlic-winter",
    categorySlug: "growing-secrets",
    title: "Слой мульчи над озимым чесноком",
    text: "После промерзания почвы лёгкий слой соломы или листвы держит стабильную температуру и меньше вымывания зубчиков морозами без снега.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Hay_bale.jpg",
    imageAlt: "Мульча",
    sortOrder: 126,
  },
  {
    slug: "hack-water-windbreak",
    categorySlug: "watering-irrigation",
    title: "Ветрозащита у капельного полива",
    text: "Низкий штакетник или сетка с западной стороны уменьшает испарение с мокрой почвы после полива в жару — полезно на открытых участках.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Rain_barrel.jpg",
    imageAlt: "Вода на участке",
    sortOrder: 127,
  },
  {
    slug: "hack-oyster-shell-path",
    categorySlug: "plot-improvement",
    title: "Дроблёная ракушка или ракушняк на дорожки",
    text: "Светлая крошка отражает свет, меньше нагревается летом и даёт кальций смывом в почву по краям грядок.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Broken_eggshell.jpg",
    imageAlt: "Светлая крошка",
    sortOrder: 128,
  },
  {
    slug: "hack-keyhole-garden",
    categorySlug: "plot-improvement",
    title: "Круглая грядка с корзиной для компоста в центре",
    text: "Классический «keyhole»: компост в середине питает кольцо грядки капиллярно; удобно для маленького огорода и экономии полива.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Compost_heap.jpg",
    imageAlt: "Компост и грядка",
    sortOrder: 129,
  },
  {
    slug: "hack-drip-from-hose",
    categorySlug: "watering-irrigation",
    title: "Простейший капельный шланг с проколами",
    text: "На садовом шланге делают мелкие проколы иглой через 20–30 см, один конец зажимают, второй на медленную воду — временная сеть для грядки на сезон.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Bottle_irrigation.jpg",
    imageAlt: "Полив",
    sortOrder: 130,
  },
  {
    slug: "hack-egg-carton-seeds",
    categorySlug: "growing-secrets",
    title: "Лотки из-под яиц для рассады",
    text: "Картонные ячейки заполняют грунтом, сеют по 1–2 семени крупных культур; при высадке дно слегка разрывают для корней. Биоразлагаемо и бесплатно.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Broken_eggshell.jpg",
    imageAlt: "Яичная упаковка",
    sortOrder: 131,
  },
  {
    slug: "hack-vine-tomato-support",
    categorySlug: "growing-secrets",
    title: "Шпалера «верёвка с потолка» для индетерминантных томатов",
    text: "В теплице вертикальная нейлоновая шнуровка с верхней балки и мягкие подвязки под кисть — меньше тени между кустами, чем у решёток.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Mustard_Fields.jpg",
    imageAlt: "Вертикальный сад",
    sortOrder: 132,
  },
  {
    slug: "hack-duck-weed-tea",
    categorySlug: "folk-simple",
    title: "Настой ряски или элодеи (осторожно с запахом)",
    text: "Водоросли и ряску настаивают 10–14 дней, разбавляют 1:10 и поливают только под корень декоративных и неядовитых культур; источник микроэлементов из водоёма.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Rain_barrel.jpg",
    imageAlt: "Водная среда",
    sortOrder: 133,
  },
  {
    slug: "hack-basil-tomato-companion",
    categorySlug: "growing-secrets",
    title: "Базилик рядом с томатом",
    text: "Аромат базилика маскирует часть вредителей и удобен на кухне; высокие томаты не затеняйте низким базиликом с южной стороны.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Tagetes_erecta_flower.jpg",
    imageAlt: "Пряные растения",
    sortOrder: 134,
  },
  {
    slug: "hack-carrot-onions-companion",
    categorySlug: "growing-secrets",
    title: "Морковь и лук вперемешку в борозде",
    text: "Лук отпугивает морковную муху запахом, морковь — луковую муху; схема «полосками» экономит место на маленькой грядке.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Onions.jpg",
    imageAlt: "Лук",
    sortOrder: 135,
  },
  {
    slug: "hack-wood-ash-berries",
    categorySlug: "soil-compost-mulch",
    title: "Зола под ягодники раз в 2–3 года",
    text: "После анализа почвы и при низком калии — просеянная зола 50–100 г/м² под перекопку осенью; на торфяных почвах эффект заметнее.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/Wood_ash.jpg",
    imageAlt: "Зола",
    sortOrder: 136,
  },
  {
    slug: "hack-epsom-pepper",
    categorySlug: "folk-simple",
    title: "Сульфат магния для перца при хлорозе листа",
    text: "10–15 г эпсомской соли на 10 л воды — разовый полив при визуальном дефиците магния (жилки зелёные, межжилье жёлтое). Не смешивайте с известью.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Coffee_grounds.jpg",
    imageAlt: "Минеральная подкормка",
    sortOrder: 137,
  },
  {
    slug: "hack-fall-leaf-mold",
    categorySlug: "soil-compost-mulch",
    title: "Перепревшие листья дуба и липы как мульча",
    text: "Год простоявшие в мешках листья превращаются в рыхлый leaf mold — мульча для клубники и кислолюбивых без сырости необработанного листа.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Pine_needles.jpg",
    imageAlt: "Листья и хвоя",
    sortOrder: 138,
  },
  {
    slug: "hack-snow-shovel-insulation",
    categorySlug: "plot-improvement",
    title: "Снег вокруг молодых деревьев",
    text: "Подсыпайте снег к стволу в открытую зиму: воздух в снегу — изолятор, меньше промерзания корневой шейки при отсутствии мульчи.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Wooden_pallet.jpg",
    imageAlt: "Зимний участок",
    sortOrder: 139,
  },
];
