/** Первые 20 лайфхаков (перенос из прежнего хардкода) + привязка к новым категориям. */
export const LEGACY_GUIDE_HACKS: {
  slug: string;
  categorySlug: string;
  title: string;
  text: string;
  imageUrl: string;
  imageAlt: string;
  sortOrder: number;
}[] = [
  {
    slug: "hack-shell-calcium",
    categorySlug: "soil-compost-mulch",
    title: "Яичная скорлупа вместо покупной извести",
    text: "Высушите скорлупу, разомните в крошку или перемелите на кофемолке и вмешайте в почву при перекопке или добавьте в лунку под рассаду. Кальций медленно отдаётся растениям и помогает предотвратить вершинную гниль у томатов и перца. На кислых почвах не заменяет доломит, но как добавка полезна.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Broken_eggshell.jpg",
    imageAlt: "Куски яичной скорлупы крупным планом",
    sortOrder: 0,
  },
  {
    slug: "hack-coffee-grounds",
    categorySlug: "soil-compost-mulch",
    title: "Кофейная гуща на грядку",
    text: "Остывшую гущу вносят в компост или тонким слоем под мульчу вокруг ягод и кустов. Органика и микроэлементы стимулируют почвенную жизнь; важно не переборщить: кофе слегка подкисляет среду — для клубники и роз часто к месту, для известковых любителей — умеренно.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Coffee_grounds.jpg",
    imageAlt: "Кофейная гуща",
    sortOrder: 1,
  },
  {
    slug: "hack-wood-ash",
    categorySlug: "folk-simple",
    title: "Древесная зола против слизней и для подкормки",
    text: "Просеянную золу рассыпают тонкой полосой вдоль грядок: слизни не любят сухую щёлочную кромку. Вносят и как источник калия и фосфора под корнеплоды после анализа почвы: на кислых участках эффект заметнее, на щелочных — экономьте золу.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/Wood_ash.jpg",
    imageAlt: "Древесная зола",
    sortOrder: 2,
  },
  {
    slug: "hack-bread-yeast-spray",
    categorySlug: "folk-simple",
    title: "Хлебный настой как мягкий стимулятор",
    text: "Небольшой кусок дрожжевого хлеба или 1 ч. л. сухих дрожжей разводят в тёплой воде с ложкой сахара, настаивают 2–3 часа, процеживают и разбавляют ведром воды. Поливают под корень утром не чаще раза в две недели в период роста — источник микроэлементов и органики; не путать с полноценной минеральной подкормкой.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Baking_yeast_cells_under_40x_microscope_objective.jpg",
    imageAlt: "Дрожжи",
    sortOrder: 3,
  },
  {
    slug: "hack-onion-peel-decoction",
    categorySlug: "folk-simple",
    title: "Отвар луковой шелухи от рассады до полива",
    text: "Шелуху лука заливают водой, кипят сорок минут, охлаждают и разбавляют чистой водой 1:5. Используют для замачивания семян (10–12 ч), полива рассады или опрыскивания: флавоноиды мягко подавляют грибковую микрофлору. Перед обработкой всей грядки проверьте реакцию на паре листьев.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Onions.jpg",
    imageAlt: "Луковицы разных сортов",
    sortOrder: 4,
  },
  {
    slug: "hack-nettle-manure",
    categorySlug: "soil-compost-mulch",
    title: "Крапивное удобрение (настой)",
    text: "Молодую крапиву без семян укладывают в бочку, заливают водой на четверть выше, накрывают марлей. Через 10–14 дней брожения разбавляют водой 1:10 и поливают капусту, томаты, огурцы. Азот и микроэлементы; запах сильный — бочку держите подальше от дома.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Urtica_dioica_pokr%C3%B3j2_23.06.2012_p.jpg",
    imageAlt: "Крапива",
    sortOrder: 5,
  },
  {
    slug: "hack-banana-potassium",
    categorySlug: "growing-secrets",
    title: "Банановая кожура для калия",
    text: "Высушите кожуру, измельчите и вносите в лунки при посадке томатов и цветков или добавьте в компост. Калий помогает завязи и окраске плодов; избыток «банана» не заменит полный состав удобрений.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Banana_peel.jpg",
    imageAlt: "Банановая кожура",
    sortOrder: 6,
  },
  {
    slug: "hack-bottle-drip",
    categorySlug: "watering-irrigation",
    title: "Капельный полив из пластиковой бутылки",
    text: "В крышке бутылки прокалывают 1–3 отверстия иглой, перевёрнутую бутылку закапывают у корня на 15–20 см. Наполняют водой — влага уходит сутками, корни тянутся вглубь. Удобно для теплицы и контейнеров в отпускной сезон.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Bottle_irrigation.jpg",
    imageAlt: "Капельный полив",
    sortOrder: 7,
  },
  {
    slug: "hack-compost-lasagna",
    categorySlug: "soil-compost-mulch",
    title: "Многослойный компост на месте грядки",
    text: "На газоне или жёстком участке укладывают картон, слой органики, земли, снова органику — как слоёный пирог. За сезон материал проседает, почва рыхлеет, черви подтягиваются сами. Подходит для новых грядок без тяжёлой лопаты.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Compost_heap.jpg",
    imageAlt: "Компостная куча",
    sortOrder: 8,
  },
  {
    slug: "hack-mustard-green-manure",
    categorySlug: "soil-compost-mulch",
    title: "Горчица сидератом вместо «запрещённой химии»",
    text: "Белую или сарептскую горчицу сеют густо после уборки ранних культур, через 5–6 недель скашивают или заделывают. Корни разрыхляют почву, биомасса подавляет часть почвенных вредителей и готовит грядку к весне.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Mustard_Fields.jpg",
    imageAlt: "Цветущая горчица",
    sortOrder: 9,
  },
  {
    slug: "hack-pine-needles-acid",
    categorySlug: "soil-compost-mulch",
    title: "Хвоя и дёготь для кислой клумбы",
    text: "Сухую хвою мельчают и добавляют в субстрат для черники, брусники и рододендронов; перепревшая хвоя держит pH ниже нейтрали. Смолистый запах отпугивает муравьёв на дорожках — укладывают полосами.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/40/Pine_needles.jpg",
    imageAlt: "Хвоя сосны",
    sortOrder: 10,
  },
  {
    slug: "hack-straw-mulch",
    categorySlug: "soil-compost-mulch",
    title: "Соломенная мульча против сорняков и перегрева",
    text: "Слой соломы 8–12 см у корней томатов, кабачков и ягодников снижает испарение и подавляет сорняки. Влага после полива держится дольше; под соломой не формируется корка после дождя.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Hay_bale.jpg",
    imageAlt: "Тюк сена или соломы",
    sortOrder: 11,
  },
  {
    slug: "hack-vinegar-path",
    categorySlug: "plot-improvement",
    title: "Уксус по бордюрам против спорных сорняков",
    text: "9% уксус разбавляют водой 1:1 и точечно обрабатывают щели в плитке и щели дорожек в жару. Обжигает листья сорняков; не брызгайте на культурные растения и не злоупотребляйте — микрожизнь почвы тоже чувствительна.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Vinegar.jpg",
    imageAlt: "Уксус",
    sortOrder: 12,
  },
  {
    slug: "hack-rain-barrel",
    categorySlug: "watering-irrigation",
    title: "Сбор дождевой воды с крыши",
    text: "Вода без хлора мягче для полива рассады и комнатных растений. Добавьте сетку от листьев и перелив; первые минуты дождя сливают в сторону — смывает пыль с кровли. Ёмкость прикрывают от комаров и мусора.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Rain_barrel.jpg",
    imageAlt: "Дождевая бочка",
    sortOrder: 13,
  },
  {
    slug: "hack-pallet-bed",
    categorySlug: "plot-improvement",
    title: "Высокая грядка из поддонов без пилы",
    text: "Чистые EUR-паллеты выкладывают двойным контуром, внутрь укладывают картон на дно, затем ветки, компост и землю. Удобно спине, быстро обогревается весной. Проверьте маркировку: не используйте обработанные импортные поддоны с ядовитыми пропитками.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Wooden_pallet.jpg",
    imageAlt: "Деревянные поддоны",
    sortOrder: 14,
  },
  {
    slug: "hack-garlic-soak",
    categorySlug: "growing-secrets",
    title: "Замачивание чеснока перед озимой посадкой",
    text: "Зубчики на час-два опускают в слабый раствор марганцовки или настой золы, затем на сутки в слегка подогретую воду — пробуждают ростки, снижают риск гнили в холодной земле. Высушите перед высадкой.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Garlic_bulbs.jpg",
    imageAlt: "Чеснок",
    sortOrder: 15,
  },
  {
    slug: "hack-nasturtium-trap",
    categorySlug: "pests-diseases-care",
    title: "Настурция-«ловушка» для тли",
    text: "Пахучую настурцию сеют по краю теплицы и грядок: тля часто садится на неё раньше, чем на томаты. Поражённые кусты вырывают и уничтожают — дешёвый индикатор и приманка.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/Nasturtium_flower_orange.jpg",
    imageAlt: "Настурция",
    sortOrder: 16,
  },
  {
    slug: "hack-wood-chip-path",
    categorySlug: "plot-improvement",
    title: "Тропинка из щепы без бетона",
    text: "На утрамбованный грунт кладут геотекстиль и 10–15 см древесных щепок; за год материал оседает и спекается в удобную бурую дорожку. Воду пропускает, сорняк почти не пробивается, выглядит органично.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/30/Woodchips.jpg",
    imageAlt: "Древесная щепа",
    sortOrder: 17,
  },
  {
    slug: "hack-vermicompost-bins",
    categorySlug: "soil-compost-mulch",
    title: "Вермикомпост в ящике на балконе или в подвале",
    text: "Червь старатель (Eisenia fetida) перерабатывает кухонные отходы в «чай» и гумус без запаха при правильной влажности. Контейнер с отверстиями, слоями картона и пищевыми отходами без цитрусов и лука — готовый подкормочный отстой через 2–3 месяца работы.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Vermicompost.jpg",
    imageAlt: "Вермикомпост",
    sortOrder: 18,
  },
  {
    slug: "hack-marigold-nematodes",
    categorySlug: "pests-diseases-care",
    title: "Бархатцы как барьер от нематод",
    text: "Тагетес выделяют вещества, подавляющие часть видов галловых нематод в почве. Сеют плотной лентой перед клубникой или после картофеля на участках с историей «узелков» на корнях. Это помощник, не панацея при тяжёлом заражении.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Tagetes_erecta_flower.jpg",
    imageAlt: "Бархатцы",
    sortOrder: 19,
  },
];
